### ISSUE TITLE
Store voting strategies at the proposal level. 

### ISSUE THREAD

**Issue by Orland0x** [snapshot-labs/sx-starknet#116]

**Comment by pscott** [comment]
The idea is to store voting strategies when a proposal is created so that if voting strategies of the space change while the proposal is still ongoing, the proposal still has access to its original voting strategies.
As it's currently hard to stored mapping / arrays inside of structs currently in Cairo, we decided to leave this as it is and come back maybe later on (hence this issue).

**Comment by pscott** [comment]
temporarily fixed by https://github.com/snapshot-labs/sx-core/pull/279 :) 
Leaving this open for the future

**Comment by zzuziak** [comment]
Hey @pscott , is that something that can be implemented for SOC? Will it be possible with Cairo 1.0?

**Comment by pscott** [comment]
> Hey @pscott , is that something that can be implemented for SOC? Will it be possible with Cairo 1.0?

Waiting for Cairo 1.0 to know more about it. Should be manageable but will make everything so much more expensive until we have a Data Availbility Solution so I'm not sure we'll want to implement it straight away...

As for SOC I believe it's the same argument: technically possible but will make proposals more expensive
