### ISSUE TITLE
missing mapping of proposal indexes to proposal ids in Zodiac module contract

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-starknet#392]
Currently there is no way to know which proposal id correspond to the proposal index on Zodiac module contract. This make it complicated to request execution in the UI. We should address this, one idea would be to send the proposal id and space address along with the execution hash from L2 to L1.

**Comment by Sekhmet** [comment]
Not sure I understand the description there, but proposalIndex can be read from the contract:
https://goerli.etherscan.io/address/0x196f0548e3140d2c7f6532a206dd54fbc12232a4#readContract (`proposalIndex`).

The issue is that it's impossible to translate starknet's contracts space/proposalId into that index so if we want to execute specific proposal from UI we can't do that because we have no way to finding correct proposalIndex.

**Comment by bonustrack** [comment]
Sorry got confused, just updated the issue

**Comment by bonustrack** [comment]
Closing this issue, this is not relevant anymore.
